#version 450
#extension GL_ARB_shading_language_include : enable

layout(local_size_x = 1) in;

#include "common/buffers.glsli"


void main() {
	if (gl_GlobalInvocationID.x == 0) {
		B_contour_fragment_attribs                   = ContourFragmentAttribsBuffer               (balloc_acquire(B_common_balloc_buffer, M_BUF_SIZE(ContourFragmentAttribsBuffer,                B_common_desc.num_contour_fragments)));
	}
}
