#version 450
#extension GL_ARB_shading_language_include : enable

layout(local_size_x = 64) in;

#include "common/buffers.glsli"
#include "common/math.glsli"


void main() {
	const uint pixel_edge_idx = gl_GlobalInvocationID.x;

	if (is_compacted_pixel_edge_idx_valid(int(pixel_edge_idx))) {
		const CompactedPixelEdgeNeighboursData neighbours = B_compacted_pixel_edge_neighbours.data[pixel_edge_idx];

		B_compacted_pixel_edge_filtered_midpoint.midpoint[pixel_edge_idx] = laplacian(
			B_compacted_pixel_edge_midpoints_filtering.midpoint[neighbours.prev_idx],
			B_compacted_pixel_edge_midpoints_filtering.midpoint[pixel_edge_idx],
			B_compacted_pixel_edge_midpoints_filtering.midpoint[neighbours.next_idx]
		);
	}
}
