#version 460
#extension GL_ARB_shading_language_include : require

layout(local_size_x = 64) in;

#include "common/buffers.glsli"


void main() {
	const uint pixel_edge_idx = gl_GlobalInvocationID.x;

	if (is_compacted_pixel_edge_idx_valid(int(pixel_edge_idx))) {
		const int prev_idx = B_compacted_pixel_edge_attribs.data[pixel_edge_idx].prev_idx;
		const int next_idx = B_compacted_pixel_edge_attribs.data[pixel_edge_idx].next_idx;

		const bool smoothed_is_inside = (
			load_bool(B_compacted_pixel_edge_segmentation.data[pixel_edge_idx].is_inside_initial) ||
			load_bool(B_compacted_pixel_edge_segmentation.data[      prev_idx].is_inside_initial) &&
			load_bool(B_compacted_pixel_edge_segmentation.data[      next_idx].is_inside_initial)
		);
		B_compacted_pixel_edge_attribs.data[pixel_edge_idx].is_inside = store_bool(smoothed_is_inside);
	}
}
