#version 450
#extension GL_ARB_shading_language_include : enable

layout(local_size_x = 64) in;

#include "common/buffers.glsli"
#include "common/scans.glsli"

void main() {
	const uint pixel_edge_idx = gl_GlobalInvocationID.x;

	if (is_fragmented_pixel_edge_idx_valid(int(pixel_edge_idx))) {
		const FragmentedPixelEdgeWyllieData data = B_fragmented_pixel_edge_wyllie.data[pixel_edge_idx][0];

		B_fragmented_pixel_edge_local_idx.local_idx[pixel_edge_idx] = int(data.value) - 1;
	}
}
